INSERT INTO PETS(ID, NAME, SPECIES, BREED, CREATE_DATE)
VALUES (1, 'Ahdul', 'Dog', 'Shih-tzu', NOW());

INSERT INTO PETS(ID, NAME, SPECIES, BREED, CREATE_DATE)
VALUES (2, 'Neil', 'Fish', 'Gold Fish', NOW());
